### ISSUE TITLE
Differentiating different forms of DIDComm messages

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/didcomm-messaging#220] opened 2021-07-06 05:07 UTC
Related to #198

**Problem Summary**
Given a 0-RTT flow where a presentation request is being sent via a URL such as `https://example.com?didcomm=<base64url encoded JWE JSON message, base64url encoded DIDComm plaintext or compact JWS>` how should we differentiate between the various message formats?

**Potential solutions**
1. Define a method to serialize the messages into a URI and content inspect
percentEncodeForUrl(didcomm://<DIDCommJWE/JWM/JWS>)

So the URL would look like this:
`https://example.com?didcomm=percentEncodeForUrl(didcomm://<DIDCommJWE/JWM/JWS>)`

In this case we'd need to do content inspection though which is a tradeoff.

2. Similar to option 1, but rather than content inspecting leverage a way to pass a media type.

Two ideas of how to do this are
2.a: `didcomm://<DIDCommJWE/JWM/JWS>?type=<media-types>`
2.b: `<media-type>://<DIDCommJWE/JWM/JWS>`

3. Content inspect directly (this is what we do for OOB)
This method is effectively what we're doing for OOB as well. However, because OOB only utilizes the JWS format it's not commonly encountered.

example: `https://example.com?didcomm=<DIDCommJWE/JWM/JWS>`

**Why does this matter?**
The main reason this is advantageous is that it makes a common format that ideally can be passed across any transport very easily without any reliance on the transport itself. This common format allows for us to have a common point where we can take any transport (QR/Bluetooth/HTTP URL/HTTP POST/etc) and go from the bespoke transport encoding to a common URI format which abstracts the complexity of transports away from the processing logic of the variety of DIDComm messages.

@dhh1128 I know you had a concern with relying too heavily on the transport. First off does this problem resonate with you and second does any of these solutions stand out as better or worse to you?

**Comment by dhh1128** [comment] 2021-07-06 07:10
I think this is a great question. I don't have a strong opinion about the answer, but I would point out that what we are really doing here is defining another transport for DIDComm -- the URI transport. (And that transport in turn defines another transport, QR codes.)

Let's create a transport doc for it, where we put the answers -- instead of treating URIs as a special topic different from transport.

**Comment by awoie** [comment] 2021-07-06 13:15
As outlined in #198 , `typ` property can be inspected for all cases, i.e., JWS/JWE/Plain. I thought we didn't support compact serialization for both JWS and JWE, primarily since it does not support multiple recipients. I'd assume on the transport the media type will be set as well but in the problem you described that won't be needed.

**Comment by kdenhartog** [comment] 2021-07-07 00:27
> @kdenhartog As outlined in #198 , `typ` property can be inspected for all cases, i.e., JWS/JWE/Plain (all of them are JSON constructs with a `typ`). I thought we didn't support compact serialization for both JWS and JWE, primarily since it does not support multiple recipients. I'd assume on the transport the media type will be set as well but in the problem you described that won't be needed.
> 
> But I'm ok with adding `typ` to the OOB (instead of `type` which indicates the type of the protocol message rather than the media type).
> 
> _**Updated**_
> I think it would be easier to stick to JSON serialization in all cases and just base64url encode them (we could support flattened and general).

That's correct, the problem comes in that when base64url encoding/decoding the JSON serialization of a JWE, it's effectively just a string where as the JWS compact is base64url with its own syntax parsing method. Since the transport layer often times requires a level of encoding/decoding it means what we effectively have to first figure out the proper decoding method we need to use in order to rely upon the `typ` and `cty` properties.

We can obviously make something up, but it needs to be something standard across implementations for the transport layer. Otherwise we're potentially going to be encoding and decoding messages into the transport layers in non interoperable ways.

**Comment by Baha-sk** [comment] 2021-07-07 04:39
>I think it would be easier to stick to JSON serialization in all cases and just base64url encode them (we could support flattened and general).

Both flattened JSON and compact serializations are for single recipient JWE envelopes. These only work when sending a message to a single recipient. I would also add that compact serialization does not use the `aad` [section of JWE](https://datatracker.ietf.org/doc/html/rfc7516#section-3.1) either, that's another reason why compact serialization is not recommended.

I'm in favour of using `typ` and `cty` protected headers to identify the DIDcomm message, in fact this is what is commonly called [Media Type](https://github.com/decentralized-identity/didcomm-messaging/blob/master/docs/spec-files/message_structure.md#message-types) in the specs.

I believe this quote in the [DIDComm Encrypted Message](https://github.com/decentralized-identity/didcomm-messaging/blob/master/docs/spec-files/message_structure.md#didcomm-encrypted-message) section should be highlighted in bold/underlined that mentions exactly the use of `typ` and `cty` headers:
>The media type of the envelope MUST be set in the `typ` property of the JWE and the media type of the payload MUST be set in the `cty` property of the JWE.

**Comment by kdenhartog** [comment] 2021-07-07 11:08
> > I think it would be easier to stick to JSON serialization in all cases and just base64url encode them (we could support flattened and general).
> 
> Both flattened JSON and compact serializations are for single recipient JWE envelopes. These only work when sending a message to a single recipient. I would also add that compact serialization does not use the `aad` [section of JWE](https://datatracker.ietf.org/doc/html/rfc7516#section-3.1) either, that's another reason why compact serialization is not recommended.
> 
> I'm in favour of using `typ` and `cty` protected headers to identify the DIDcomm message, in fact this is what is commonly called [Media Type](https://github.com/decentralized-identity/didcomm-messaging/blob/master/docs/spec-files/message_structure.md#message-types) in the specs.
> 
> I believe this quote in the [DIDComm Encrypted Message](https://github.com/decentralized-identity/didcomm-messaging/blob/master/docs/spec-files/message_structure.md#didcomm-encrypted-message) section should be highlighted in bold/underlined that mentions exactly the use of `typ` and `cty` headers:
> 
> > The media type of the envelope MUST be set in the `typ` property of the JWE and the media type of the payload MUST be set in the `cty` property of the JWE.

I'm not following how this helps with knowing the encoding at the transport layer though. If the transport layer doesn't require any encoding such as an HTTP post then sure one could content inspect and recognize the type from the payload itself. However, for transports that do require an encoding scheme this seems like it wouldn't help in this case as the `cty` and `typ` properties are encoded. Am I missing something?

**Comment by Baha-sk** [comment] 2021-07-07 14:30
>I'm not following how this helps with knowing the encoding at the transport layer though. If the transport layer doesn't require any encoding such as an HTTP post then sure one could content inspect and recognize the type from the payload itself. However, for transports that do require an encoding scheme this seems like it wouldn't help in this case as the cty and typ properties are encoded. Am I missing something?

I thought the discussion was about the benefits of compact vs Flattened JSON vs normal Full JSON serializations.

Indeed these headers are available at the message layer, not the transport layer @kdenhartog. It would be hard to know the media type if it's exchanged using TLS, which is 99.99% the case.

A URI identifier would make more sense then if we want multi transport interop (to avoid relying on HTTP headers).

**Comment by kdenhartog** [comment] 2021-07-08 00:22
> I thought the discussion was about the benefits of compact vs Flattened JSON vs normal Full JSON serializations.

Ahh that makes sense about your response now. Yeah I was more thinking about how types would be used to identify things.

>A URI identifier would make more sense then if we want multi transport interop (to avoid relying on HTTP headers).

Yeah that's kind of what I was thinking as well. So essentially all messages get normalized into a URI first and then the URI is placed into the transport layer. I think @dhh1128 was thinking of similar requirements of not wanting to rely upon the transport layer for conveying type as well because it would be potentially restrictive to transport layers which are not designed to convey a media-type. QR codes are a good example of this.

**Comment by dhh1128** [comment] 2021-07-08 08:12
>I think @dhh1128 was thinking of similar requirements of not wanting to rely upon the transport layer for conveying type as well because it would be potentially restrictive to transport layers which are not designed to convey a media-type. QR codes are a good example of this.

Yes. To be clear, I think the case where a DIDComm message is transmitted over only one transport is going to be common and easy to analyze -- but I want our designs to include thoughts about what happens when the transport changes halfway through a route. In other words, I don't just want "DIDComm over HTTP" to work in isolation; I want it to work as part of a multi-transport route that includes "DIDComm over something else" as well. Therefore I have always been leery of simplifications that work only for one transport.

**Comment by kdenhartog** [comment] 2021-07-15 02:21
Related to #222, these discussions are close enough that I suspect we could clear them both up on a call.

**Comment by awoie** [comment] 2021-07-15 11:46
What if OOB is its own transport, then we can defer the media type to the transport layer. OOB is essentially just a special URL transport. Thoughts?

**Comment by TelegramSam** [comment] 2021-07-30 17:36
I do think of OBB as its own transport, and as such can be adapted to serve the needs of passing DIDComm messages.

**Comment by kdenhartog** [comment] 2021-08-02 04:22
I was thinking of OOB payload (not the fully formed URL) as more of a repeatable discovery protocol. E.g. it can be used to convey information necessary to bootstrap the connection, but it could also be sent after a connection has been established to update relevant state of the connection. This would make it more along the lines of a protocol that sits at the same layer of trust ping and instead the URL layer could be generalized to pass any message rather than requiring the usage of a POST with HTTP. By doing this we could then use HTTP GET where a relay could just perform a 302 redirect to pass the message onto the next hop.

**Comment by TelegramSam** [comment] 2021-08-06 13:16
@kdenhartog What do you see as the division of responsibility between the feature discovery protocol vs OOB?

I have been thinking of OOB as only containing the info needed to bootstrap into a deeper interaction around feature discovery.

**Comment by Baha-sk** [comment] 2021-08-06 18:05
One thing i'm noticing with OOB invitations vs other DID connected DIDcomm requests is the fact that the sender key is not, yet, known to the recipient since it doesn't have the sender DID yet when unpacking the invitation request. 

This means OOB invitations must use `anoncrypt()` to build the request envelope to avoid resolving the `skid`.  The payload in that envelope will still contain all the needed info to bootstrap a new did connection.

Currently all DIDComm (prior to V2) interactions use `authcrypt`, including OOB invitations since keys are base58 encodings of X25519 keys, ie there's no key resolution needed. With DIDComm v2 however, keys must be resolved from KeyAgreement.ID values so the toDID and fromDID documents are required to resolve skid/kid headers.

@TelegramSam @kdenhartog any objections to this `anoncrypt` (instead of `authcrypt`) constraint for OOB invitations only? cc @dhh1128, @awoie, @andrewwhitehead @swcurran @troyronda 

This is probably not a question about division of responsibility between discovery protocol vs OOB, but since the issue is about differentiating between the different forms of DIDcomm messages, the request handling of OOB invitations should also differ from other DIDcomm messages, ie use `anoncrypt` for OOB invitations and `authcrypt` for all other requests.

**Comment by swcurran** [comment] 2021-08-06 18:12
Isn't the point of out-of-band messages that they are by definition plaintext?  OOB is used when the inviter has no knowledge of the DIDComm capabilities (e.g. no DID, no connection) of the recipient.  It is a plaintext message that contains a way for the recipient to send a DIDComm message back.

**Comment by Baha-sk** [comment] 2021-08-06 18:29
>Isn't the point of out-of-band messages that they are by definition plaintext? OOB is used when the inviter has no knowledge of the DIDComm capabilities (e.g. no DID, no connection) of the recipient. It is a plaintext message that contains a way for the recipient to send a DIDComm message back.

Technically this is correct, but we still pack them to protect the requests in afgo.

if we remove the packing (ie plaintext), then there's no need to resolve anything but the message exchanged is not protected.

**Comment by swcurran** [comment] 2021-08-06 20:31
I don't get how that works.  The sender of the OOB invite doesn't have an encryption key for the recipient, nor does the recipient for the sender.  You could send it with the message, but that is protecting the request.  Am I missing something?

**Comment by Baha-sk** [comment] 2021-08-06 21:43
Apparently it's not in the oob invitation but after the invitation call is done during the did exchange request, when Bob receives Alice's DID, the envelope has `skid=Alice's DID#keyAgreementID` but since Bob doesn't have the DID yet, he can't resolve keyAgreementID and therefore can't decrypt the envelope. I noticed this when i switched the kid/skid headers be KeyAgreement.IDs in our bdd tests.

I think using kid values as `did:key` in this special case (or when communicating without DIDs) would make sense?

**Comment by swcurran** [comment] 2021-08-06 23:50
Assuming Alice is the Inviter (sends to the OOB) and Bob is the invitee (receives it).  The following is based on how OOB works in Aries/DIDComm 1, but I would assume it still applies.

Bob gets from the OOB a keyAgreement key and an endpoint (e.g. a full service block), so effectively he does have a "DID" for Alice.  It may not be a the final DID for the connection (Alice may use the same DID for all her OOB invitations), but it is (or should be) a proper DID.  It could be because Alice included in the OOB a published DID that Bob can resolve, or because Alice included an in-line Service block with the necessary `recipientKeys` and `routingKeys`.

Notes on that:

1. I believe in DIDComm2, the `service` block assumes the `recipientKeys` array based on the DIDDoc -- not sure how that detail is addressed.  Perhaps that trap that you are talking about?
2. It is an option in Aries that the Alice can use an expanded `did:key` that embeds a full DIDDoc, including the necessary DIDComm `service` block so that she does not have to put the DID on a ledger, but rather can send it inline.

In your comment above, you say a `did:key` could be used. Is that to imply that the `did:key` can have a single key and derive the keyAgreement key from the verkey where possible?

**Comment by kdenhartog** [comment] 2021-08-07 06:14
Since the oob discussion was straying a bit from what I originally wanted to cover here, I opened a separate issue for it. That's over in #250

For this one, my main concern I was looking to address is checking if it would make sense to serial all messages into a URI format before embedding it onto a transport.

**Comment by Baha-sk** [comment] 2021-08-09 13:39
> It could be because Alice included in the OOB a published DID that Bob can resolve, or because Alice included an in-line Service block with the necessary recipientKeys and routingKeys.

Apparently DIDComm V2 service bloc does not have `recipientKeys`  https://identity.foundation/didcomm-messaging/spec/#did-document-service-endpoint.

A similar discussion is found in issue #191 (see @awoie's [comment](https://github.com/decentralized-identity/didcomm-messaging/issues/191#issuecomment-885475551) which is now guiding my findings on key resolution from the service block).

> In your comment above, you say a did:key could be used. Is that to imply that the did:key can have a single key and derive the keyAgreement key from the verkey where possible?

The `did:key` is nothing else than the literal `did:key:` string + multi-base representation of a public key, applications should be able to extract the raw key value directly from the multi-base part. 

As noted in the comments of #191, the source of the `did:key` cannot be authenticated though, therefore not recommended in this context. But if the recipient does not have the sender's DID doc yet, how can the sender be authenticated?

In V1, keys were base58 encoded, so there's no resolution. In V2, the encryption layer cannot resolve skid if the sender's DID doc is not available to dereference skid=keyAgreement.ID. 

@kdenhartog my apology for hijacking this issue. I should have continued the conversation in #191.

**Comment by kdenhartog** [comment] 2021-08-10 11:08
> @kdenhartog my apology for hijacking this issue. I should have continued the conversation in #191.

All good, it's all in good faith and all issues we need to sort out.

**Comment by Baha-sk** [comment] 2021-09-17 16:28
Since the discussion in this issue has diverted a bit, i believe this [PR](https://github.com/decentralized-identity/didcomm-messaging/pull/286) closes this discussion. I'll link this issue to it. Unfortunately, the issue title is misleading, but i'm glad @kdenhartog created a separate issue (#191) for it.

**Comment by TelegramSam** [comment] 2022-01-10 20:52
Closed after discussion in 20220110.

**Closed by TelegramSam** 2022-01-10 20:52 UTC
Labels: needs discussion, v2.0
